apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # Allow manifests to deploy from any Git repos
  source:
    path: src/application
    repoURL: https://github.com/lai85321/SRE-task-6-3.git
    targetRevision: main
  destination:
    namespace: default
    server: https://kubernetes.default.svc
