name: Approval to Merge

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"Need your approval: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}" \
          $DISCORD_WEBHOOK

  check-approvals:
    runs-on: ubuntu-latest
    needs: notification
    steps:
      - name: Check approvals
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const approvals = pullRequest.reviews.filter(review => review.state === 'APPROVED').length;
            core.setOutput('approvals', approvals);

  manual-approval:
    runs-on: ubuntu-latest
    needs: [notification, check-approvals]
    if: steps.check-approvals.outputs.approvals >= 2
    steps:
      - name: Manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          approvers: lai85321
          minimum-approvals: 1
