name: Approval to Merge

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"Need your approval: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}" \
          $DISCORD_WEBHOOK
  manual-approval:
    runs-on: ubuntu-latest
    needs: notification
    steps:
      - name: Manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          approvers: lai85321
          minimum-approvals: 2
